name: 'SSH Remote Commands'
description: 'Executing remote ssh commands'
author: 'Bo-Yi Wu'
inputs:
  host:
    description: 'ssh remote host'
  port:
    description: 'ssh remote port'
    default: 22
  passphrase:
    description: 'ssh key passphrase'
  username:
    description: 'ssh username'
  password:
    description: 'ssh password'
  timeout:
    description: 'timeout for ssh to remote host'
    default: "30s"
  command_timeout:
    description: 'timeout for ssh command'
    default: "10m"
  key:
    description: 'content of ssh private key. ex raw content of ~/.ssh/id_rsa'
  key_path:
    description: 'path of ssh private key'
  proxy_host:
    description: 'ssh proxy remote host'
  proxy_port:
    description: 'ssh proxy remote port'
    default: 22
  proxy_username:
    description: 'ssh proxy username'
  proxy_password:
    description: 'ssh proxy password'
  proxy_passphrase:
    description: 'ssh proxy key passphrase'
  proxy_timeout:
    description: 'timeout for ssh to proxy host'
    default: "30s"
  proxy_key:
    description: 'content of ssh proxy private key. ex raw content of ~/.ssh/id_rsa'
  proxy_key_path:
    description: 'path of ssh proxy private key'
  script:
    description: 'execute commands'
  script_stop:
    description: 'stop script after first failure'
    default: false
  envs:
    description: 'pass environment variable to shell script'
  debug:
    description: 'enable debug mode'
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'terminal'
  color: 'gray-dark'
